// import './globals.css'
"use client";
import { Inter } from "next/font/google";
import Box from "@mui/material/Box";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });
import { createTheme, ThemeProvider, styled } from "@mui/material/styles";
import css from "../components/Baground.module.css";
const globalTheam = createTheme({
  components: {
    // Name of the component
    MuiButton: {
      styleOverrides: {
        // Name of the slot
        contained: {
          // Some CSS
          // fontSize: "1rem",
          // border: "10px solid",
          color: "#ffff",
          textTransform: "none",
          backgroundColor: "#f36623",
          borderRadius: "15px",
          padding: "10px 15px 10px 15px",
          "&:hover": {
            backgroundColor: "#f36623",
          },
        },
        text: {
          padding: "0px",
        },
      },
    },
  },
  palette: {
    primary: {
      main: "#f36623",
    },
  },
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        style={{ margin: "0" }}
        className={inter.className}
        suppressHydrationWarning={true}
      >
        <ThemeProvider theme={globalTheam}>
          <Box className={css.bg}>
            <Box
              sx={{
                marginRight: "auto",
                marginLeft: "auto",
              }}
              maxWidth="1280px"
              // className={css.bg}
            >
              <Header />
              {children}
            </Box>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
